<?php

use Drupal\Component\Utility\SafeMarkup;
use Drupal\Core\Url;

function genericcontactform_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];

  switch ($key) {
    case 'form_submit_notification':
    
      $msgbody  = 'This is to notify you that the following values were submitted to the ';
      $msgbody .= 'Generic Contact Form.' . chr(10) . chr(10);
      
      $msgbody .= 'Name: ' . $params['name'] . chr(10);
      $msgbody .= 'Email: ' . $params['email'] . chr(10);
      $msgbody .= 'Color: ' . $params['color'] . chr(10);
      $msgbody .= 'Message: ' . $params['message'] . chr(10);

      $message['subject'] = 'Generic Contact Form Submission';

      $message['body'][] = SafeMarkup::checkPlain($msgbody);

      break;
  }
}


function genericcontactform_toolbar() {

  $items['genericcontactform'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => 'Generic Contact Form',
      '#url' => Url::fromRoute('genericcontactform_adminlist'),
      '#attributes' => [
        'title' => 'GCF',
        'class' => ['toolbar-icon', 'toolbar-icon-genericcontactform'],
      ],
    ],
    '#weight' => 99,
    '#attached' => [
      'library' => [
        'genericcontactform/genericcontactform.icons',
      ],
    ],
  ];

  return $items;

}

