<?php

use Drupal\Component\Utility\SafeMarkup;

function morningmail_mail($key, &$message, $params) {
  
  switch ($key) {
    default:
      $message['from'] = 'morningmail@rpi.edu';
      $message['subject'] = $params['subject'];
      $message['headers'] = [
        'Content-Type' => 'text/html; charset=UTF-8; format=flowed; delsp=yes',
        'MIME-Version' => '1.0',
        'Reply-to' => 'Morning Mail <mm-support@lists.rpi.edu>',
        'X-Sympa-Password' => 'password',
        'Sender' => 'morningmail@rpi.edu',
        'Return-Path' => 'morningmail@rpi.edu'
      ];
  }
  
}
